framework:
    mailer:
        dsn: "%env(MAILER_DSN)%"
        envelope:
            sender: "info@trouveunchalet.com"
        headers:
            From: "Trouve un chalet <info@trouveunchalet.com>"
