version: "3"

services:
  ###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "3306:3306"
  ###< doctrine/doctrine-bundle ###

  app:
    build:
      args:
        SUPERVISOR_BASE_STAGE: app_php_dev
    environment:
      SERVER_NAME: localhost, trouvetoncamping.local, trouvetonchalet.local

  ###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: ["1025", "1080"]
  ###< symfony/mailer ###

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - ${ADMINER_PORT:-8080}:8080
