montreal:
  slug: montreal
  name: Montréal
  latitude: 45.501690
  longitude: -73.567253
  radius: 75
  sector: Sud

laval:
  slug: laval
  name: Laval
  latitude: 45.606647
  longitude: -73.712410
  radius: 75
  sector: Sud

outaouais:
  slug: outaouais
  name: Outaouais
  latitude: 45.443619
  longitude: -73.466530
  radius: 75
  sector: Sud

monteregie:
  slug: monteregie
  name: Montérégie
  latitude: 45.416386
  longitude: -73.110435
  radius: 75
  sector: Sud

cantons-de-lest:
  slug: cantons-de-lest
  name: Cantons-de-l'Est
  latitude: 45.341080
  longitude: -72.747810
  radius: 75
  sector: Sud

# Couldn't find a decent photo to use, so... I disabled it.
# centre-du-quebec:
#   slug: centre-du-quebec
#   name: Centre-du-Québec
#   latitude: 45.88643
#   longitude: -72.501876
#   radius: 50
#   sector: Sud

abitibi-temiscamingue:
  slug: abitibi-temiscamingue
  name: Abitibi-Témiscamingue
  latitude: 48.102336
  longitude: -77.787572
  radius: 75
  sector: Ouest

laurentides:
  slug: laurentides
  name: Laurentides
  latitude: 46.11588
  longitude: -74.589143
  radius: 75
  sector: Ouest

lanaudiere:
  slug: lanaudiere
  name: Lanaudière
  latitude: 46.072798
  longitude: -73.888637
  radius: 75
  sector: Ouest

mauricie:
  slug: mauricie
  name: Mauricie
  latitude: 46.674230
  longitude: -72.873235
  radius: 75
  sector: Ouest

saguenay-lac-saint-jean:
  slug: saguenay-lac-saint-jean
  name: Saguenay–Lac-Saint-Jean
  latitude: 48.512461
  longitude: -71.886580
  radius: 125
  sector: Ouest

quebec:
  slug: quebec
  name: Québec
  latitude: 46.845573
  longitude: -71.202096
  radius: 100
  sector: Est

charlevoix:
  slug: charlevoix
  name: Charlevoix
  latitude: 47.632945
  longitude: -70.231051
  radius: 100
  sector: Est

cote-nord:
  slug: cote-nord
  name: Côte-Nord
  latitude: 50.303898
  longitude: -68.484836
  radius: 300
  sector: Est

iles-de-la-madeleine:
  slug: iles-de-la-madeleine
  name: Îles-de-la-Madeleine
  latitude: 47.38131
  longitude: -61.856525
  radius: 100
  sector: Est

gaspesie:
  slug: gaspesie
  name: Gaspésie
  latitude: 48.651910
  longitude: -66.248396
  radius: 200
  sector: Est

bas-saint-laurent:
  slug: bas-saint-laurent
  name: Bas-Saint-Laurent
  latitude: 48.158107
  longitude: -69.011067
  radius: 75
  sector: Est

chaudiere-appalaches:
  slug: chaudiere-appalaches
  name: Chaudière-Appalaches
  latitude: 45.5937941
  longitude: -70.9346429
  radius: 100
  sector: Est

nunavik:
  slug: nunavik
  name: Nunavik
  latitude: 57.213476
  longitude: -71.091996
  radius: 600
  sector: Nord

eeyou-istchee-baie-james:
  slug: eeyou-istchee-baie-james
  name: Eeyou Istchee Baie-James
  latitude: 50.553313
  longitude: -77.297946
  radius: 350
  sector: Nord
