# Before adding new entries to this config, make sure you define the keys in the `Site` enum.
chaletsalouer.com:
  url: https://www.chaletsalouer.com
  crawler: App\Crawler\Driver\ChaletsALouer
levertendre.com:
  url: https://levertendre.com
  crawler: App\Crawler\Driver\LeVertendre
wechalet.com:
  url: https://wechalet.com
  crawler: App\Crawler\Driver\WeChalet
